-- =============================================================================
-- create_company_for_user — superseded (do not maintain a duplicate here)
-- =============================================================================
--
-- This file used to be a standalone "quick fix" copy of the registration RPC.
-- The function body is now defined in two maintained places only:
--
--   1. Fresh / reference bootstrap (companies + users + RPC)
--      → Run or consult:  auth_schema.sql
--
--   2. Existing production database (replace RPC + backfill subscriptions)
--      → Run once in Supabase SQL Editor:  migrations/subscriptions_backfill_and_signup_seed.sql
--
-- That migration updates `create_company_for_user` (free-plan row on signup) and inserts
-- missing `subscriptions` rows for companies that have none.
--
-- Prerequisite: `subscription_plans` must include `name = 'free'` (see subscriptions_schema.sql).
-- =============================================================================

-- If you ran this file by mistake, ignore the result below and run:
--   migrations/subscriptions_backfill_and_signup_seed.sql
SELECT 'use migrations/subscriptions_backfill_and_signup_seed.sql' AS run_this_instead;
