"use server"

import React from "react"
import * as Sentry from "@sentry/nextjs"
import { Document, Page, Text, View, StyleSheet, pdf } from "@react-pdf/renderer"
import { createClient } from "@/lib/supabase/server"
import { getCachedAuthContext } from "@/lib/auth/server"
import { checkViewPermission } from "@/lib/server-permissions"
import { errorMessage } from "@/lib/error-message"
import { getResendClient } from "./invoice-email"

type Contractor1099Row = {
  driverId: string
  driverName: string
  driverEmail: string | null
  employeeType: string | null
  annualPayments: number
  settlementCount: number
  qualifiesFor1099: boolean
}

const styles = StyleSheet.create({
  page: { padding: 24, fontSize: 10, fontFamily: "Helvetica", color: "#111827" },
  title: { fontSize: 16, fontWeight: 700, marginBottom: 8 },
  subtitle: { fontSize: 10, color: "#4b5563", marginBottom: 16 },
  section: { marginBottom: 12, borderWidth: 1, borderColor: "#e5e7eb", padding: 10 },
  sectionTitle: { fontSize: 11, fontWeight: 700, marginBottom: 6 },
  row: { flexDirection: "row", justifyContent: "space-between", marginBottom: 4 },
  label: { color: "#6b7280", width: "45%" },
  value: { width: "55%", textAlign: "right" },
  amount: { fontWeight: 700 },
  footer: { marginTop: 12, fontSize: 9, color: "#6b7280" },
})

async function toPdfBytes(value: unknown): Promise<Uint8Array> {
  if (value instanceof Uint8Array) return value
  if (value instanceof ArrayBuffer) return new Uint8Array(value)
  if (value instanceof Blob) return new Uint8Array(await value.arrayBuffer())
  if (value && typeof value === "object" && "getReader" in value) {
    const buffer = await new Response(value as ReadableStream).arrayBuffer()
    return new Uint8Array(buffer)
  }
  throw new Error("Unsupported PDF output type")
}

function formatCurrency(value: number) {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value || 0)
}

function build1099Document(payload: {
  taxYear: number
  payerName: string
  payerEin: string | null
  payerAddress: string
  recipientName: string
  recipientTin: string | null
  recipientAddress: string
  nonemployeeComp: number
}) {
  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.title}>Form 1099-NEC (Draft)</Text>
        <Text style={styles.subtitle}>
          Nonemployee Compensation Summary - Tax Year {payload.taxYear}
        </Text>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Payer</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Business name</Text>
            <Text style={styles.value}>{payload.payerName}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>TIN / EIN</Text>
            <Text style={styles.value}>{payload.payerEin || "Not provided"}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Address</Text>
            <Text style={styles.value}>{payload.payerAddress || "Not provided"}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Recipient (Contractor Driver)</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Name</Text>
            <Text style={styles.value}>{payload.recipientName}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>TIN / SSN</Text>
            <Text style={styles.value}>{payload.recipientTin || "Not provided"}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Address</Text>
            <Text style={styles.value}>{payload.recipientAddress || "Not provided"}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Box 1 - Nonemployee Compensation</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Total paid in tax year</Text>
            <Text style={[styles.value, styles.amount]}>{formatCurrency(payload.nonemployeeComp)}</Text>
          </View>
        </View>

        <Text style={styles.footer}>
          Generated by TruckMates for operational year-end workflow. Please review with your tax advisor before filing.
        </Text>
      </Page>
    </Document>
  )
}

async function get1099Context() {
  const ctx = await getCachedAuthContext()
  if (ctx.error || !ctx.companyId) return { error: ctx.error || "Not authenticated", companyId: null as string | null }

  const canView = await checkViewPermission("accounting")
  if (!canView.allowed) return { error: canView.error || "You don't have permission", companyId: null as string | null }

  return { error: null, companyId: ctx.companyId }
}

export async function getContractor1099Summary(taxYear: number): Promise<{
  data: Contractor1099Row[] | null
  error: string | null
}> {
  try {
    if (!Number.isFinite(taxYear) || taxYear < 2000 || taxYear > 2100) {
      return { data: null, error: "Invalid tax year" }
    }

    const auth = await get1099Context()
    if (auth.error || !auth.companyId) return { data: null, error: auth.error || "Not authenticated" }

    const supabase = await createClient()
    const start = `${taxYear}-01-01`
    const end = `${taxYear}-12-31T23:59:59.999Z`

    const { data: drivers, error: driverError } = await supabase
      .from("drivers")
      .select("id, name, email, employee_type")
      .eq("company_id", auth.companyId)
      .eq("employee_type", "contractor")
      .order("name", { ascending: true })

    if (driverError) {
      return { data: null, error: "Failed to load contractor drivers" }
    }

    const driverIds = (drivers || []).map((d: { id: string }) => d.id)
    if (driverIds.length === 0) return { data: [], error: null }

    const { data: settlements, error: settlementError } = await supabase
      .from("settlements")
      .select("driver_id, net_pay")
      .eq("company_id", auth.companyId)
      .eq("status", "paid")
      .in("driver_id", driverIds)
      .gte("paid_date", start)
      .lte("paid_date", end)

    if (settlementError) {
      return { data: null, error: "Failed to load settlements for tax year" }
    }

    const totals = new Map<string, { amount: number; count: number }>()
    for (const row of settlements || []) {
      const driverId = String((row as { driver_id?: string }).driver_id || "")
      if (!driverId) continue
      const existing = totals.get(driverId) || { amount: 0, count: 0 }
      existing.amount += Number((row as { net_pay?: number }).net_pay || 0)
      existing.count += 1
      totals.set(driverId, existing)
    }

    const data: Contractor1099Row[] = (drivers || []).map((driver: any) => {
      const total = totals.get(driver.id) || { amount: 0, count: 0 }
      return {
        driverId: driver.id,
        driverName: driver.name || "Unnamed driver",
        driverEmail: driver.email || null,
        employeeType: driver.employee_type || null,
        annualPayments: total.amount,
        settlementCount: total.count,
        qualifiesFor1099: total.amount >= 600,
      }
    })

    return { data, error: null }
  } catch (error: unknown) {
    Sentry.captureException(error)
    return { data: null, error: errorMessage(error, "Failed to load 1099 summary") }
  }
}

async function generate1099PdfBuffer(driverId: string, taxYear: number): Promise<{
  pdfBuffer: Uint8Array | null
  filename: string
  error: string | null
}> {
  try {
    const auth = await get1099Context()
    if (auth.error || !auth.companyId) {
      return { pdfBuffer: null, filename: "", error: auth.error || "Not authenticated" }
    }

    const supabase = await createClient()
    const start = `${taxYear}-01-01`
    const end = `${taxYear}-12-31T23:59:59.999Z`

    const { data: driver, error: driverError } = await supabase
      .from("drivers")
      .select("id, name, email, employee_type, address, city, state, zip, license_number")
      .eq("company_id", auth.companyId)
      .eq("id", driverId)
      .eq("employee_type", "contractor")
      .maybeSingle()

    if (driverError || !driver) {
      return { pdfBuffer: null, filename: "", error: "Contractor driver not found" }
    }

    const { data: settlements, error: settlementsError } = await supabase
      .from("settlements")
      .select("net_pay")
      .eq("company_id", auth.companyId)
      .eq("driver_id", driverId)
      .eq("status", "paid")
      .gte("paid_date", start)
      .lte("paid_date", end)

    if (settlementsError) {
      return { pdfBuffer: null, filename: "", error: "Failed to load paid settlements" }
    }

    const annualTotal = (settlements || []).reduce((sum: number, row: any) => sum + (Number(row.net_pay) || 0), 0)

    const { data: company } = await supabase
      .from("companies")
      .select("name, address, city, state, zip")
      .eq("id", auth.companyId)
      .maybeSingle()

    const { data: settings } = await supabase
      .from("company_settings")
      .select("ein_number")
      .eq("company_id", auth.companyId)
      .maybeSingle()

    const payerAddress = [company?.address, [company?.city, company?.state].filter(Boolean).join(", "), company?.zip]
      .filter(Boolean)
      .join(" ")
    const recipientAddress = [driver.address, [driver.city, driver.state].filter(Boolean).join(", "), driver.zip]
      .filter(Boolean)
      .join(" ")

    const doc = build1099Document({
      taxYear,
      payerName: company?.name || "Carrier",
      payerEin: (settings as any)?.ein_number || null,
      payerAddress,
      recipientName: driver.name || "Driver",
      recipientTin: driver.license_number || null,
      recipientAddress,
      nonemployeeComp: annualTotal,
    })

    const pdfOutput = await pdf(doc).toBuffer()
    const pdfBuffer = await toPdfBytes(pdfOutput)
    const safeName = String(driver.name || "driver").trim().replace(/[^a-zA-Z0-9-_]+/g, "-")
    const filename = `1099-NEC-${safeName}-${taxYear}.pdf`
    return { pdfBuffer, filename, error: null }
  } catch (error: unknown) {
    Sentry.captureException(error)
    return { pdfBuffer: null, filename: "", error: errorMessage(error, "Failed to generate 1099 PDF") }
  }
}

export async function generate1099NECPdfBase64(driverId: string, taxYear: number): Promise<{
  base64: string | null
  filename: string | null
  error: string | null
}> {
  const generated = await generate1099PdfBuffer(driverId, taxYear)
  if (generated.error || !generated.pdfBuffer) {
    return { base64: null, filename: null, error: generated.error || "Failed to generate PDF" }
  }
  return {
    base64: Buffer.from(generated.pdfBuffer).toString("base64"),
    filename: generated.filename,
    error: null,
  }
}

export async function send1099ToDriver(driverId: string, taxYear: number): Promise<{
  data: { sent: boolean; to: string; emailId?: string } | null
  error: string | null
}> {
  try {
    const auth = await get1099Context()
    if (auth.error || !auth.companyId) return { data: null, error: auth.error || "Not authenticated" }

    const supabase = await createClient()
    const { data: driver, error: driverError } = await supabase
      .from("drivers")
      .select("id, name, email, employee_type")
      .eq("company_id", auth.companyId)
      .eq("id", driverId)
      .eq("employee_type", "contractor")
      .maybeSingle()

    if (driverError || !driver) return { data: null, error: "Contractor driver not found" }
    if (!driver.email || !String(driver.email).includes("@")) {
      return { data: null, error: "Driver email is missing or invalid" }
    }

    const generated = await generate1099PdfBuffer(driverId, taxYear)
    if (generated.error || !generated.pdfBuffer) {
      return { data: null, error: generated.error || "Could not generate PDF" }
    }

    const resend = await getResendClient()
    if (!resend) {
      return { data: null, error: "Email service not configured. Set RESEND_API_KEY first." }
    }

    let fromEmail = process.env.RESEND_FROM_EMAIL
    if (!fromEmail) {
      const { data: integrations } = await supabase
        .from("company_integrations")
        .select("resend_from_email")
        .eq("company_id", auth.companyId)
        .maybeSingle()
      if (integrations?.resend_from_email) fromEmail = integrations.resend_from_email
    }
    fromEmail = fromEmail || "onboarding@resend.dev"

    const { data: company } = await supabase
      .from("companies")
      .select("name")
      .eq("id", auth.companyId)
      .maybeSingle()
    const companyName = company?.name || "Your company"

    const emailResult = await resend.emails.send({
      from: fromEmail,
      to: [driver.email],
      subject: `${companyName} - Your ${taxYear} Form 1099-NEC`,
      text: `Hello ${driver.name || "Driver"},\n\nAttached is your Form 1099-NEC draft for tax year ${taxYear}.\n\nPlease review and contact payroll if any correction is needed.`,
      html: `<p>Hello ${driver.name || "Driver"},</p><p>Attached is your Form 1099-NEC draft for tax year ${taxYear}.</p><p>Please review and contact payroll if any correction is needed.</p>`,
      attachments: [{ filename: generated.filename, content: Buffer.from(generated.pdfBuffer) }],
    })

    if (emailResult.error) {
      return { data: null, error: `Failed to send email: ${emailResult.error.message || "Unknown error"}` }
    }

    return {
      data: { sent: true, to: driver.email, emailId: emailResult.data?.id },
      error: null,
    }
  } catch (error: unknown) {
    Sentry.captureException(error)
    return { data: null, error: errorMessage(error, "Failed to send 1099 to driver") }
  }
}

