-- Insert Demo Marketplace Loads
-- Updated for current platform state with all available fields
-- 
-- Usage: Run this script in your Supabase SQL editor or via psql
-- The script will automatically find a broker company and assign loads to it
-- If you have multiple broker companies, it will use the first one it finds
--
-- IMPORTANT: Make sure you have at least one company with company_type = 'broker' or 'both'
-- If you don't have a broker company yet, create one first or change your existing company type

-- Demo Load 1: Cross-Country Dry Van (Electronics)
INSERT INTO public.load_marketplace (
  broker_id,
  origin,
  destination,
  weight,
  weight_kg,
  contents,
  value,
  rate,
  rate_type,
  pickup_date,
  pickup_time_window_start,
  pickup_time_window_end,
  delivery_date,
  delivery_time_window_start,
  delivery_time_window_end,
  equipment_type,
  status,
  auto_create_enabled,
  notes,
  shipper_name,
  shipper_address,
  shipper_city,
  shipper_state,
  shipper_zip,
  shipper_contact_name,
  shipper_contact_phone,
  shipper_contact_email,
  pickup_instructions,
  consignee_name,
  consignee_address,
  consignee_city,
  consignee_state,
  consignee_zip,
  consignee_contact_name,
  consignee_contact_phone,
  consignee_contact_email,
  delivery_instructions,
  pieces,
  pallets,
  boxes,
  length,
  width,
  height,
  temperature,
  is_hazardous,
  is_oversized,
  special_instructions,
  requires_liftgate,
  requires_inside_delivery,
  requires_appointment,
  appointment_time
)
SELECT 
  c.id as broker_id,
  'Los Angeles, CA' as origin,
  'New York, NY' as destination,
  '22.5 tons' as weight,
  20412 as weight_kg,
  'Electronics and consumer goods' as contents,
  150000.00 as value,
  8500.00 as rate,
  'flat' as rate_type,
  CURRENT_DATE + INTERVAL '3 days' as pickup_date,
  '08:00:00'::TIME as pickup_time_window_start,
  '17:00:00'::TIME as pickup_time_window_end,
  CURRENT_DATE + INTERVAL '8 days' as delivery_date,
  '09:00:00'::TIME as delivery_time_window_start,
  '16:00:00'::TIME as delivery_time_window_end,
  'dry_van' as equipment_type,
  'available' as status,
  true as auto_create_enabled,
  'Time-sensitive delivery. Requires appointment for pickup and delivery.' as notes,
  'TechCorp Distribution' as shipper_name,
  '1234 Industrial Blvd' as shipper_address,
  'Los Angeles' as shipper_city,
  'CA' as shipper_state,
  '90001' as shipper_zip,
  'John Martinez' as shipper_contact_name,
  '(555) 123-4567' as shipper_contact_phone,
  'john.martinez@techcorp.com' as shipper_contact_email,
  'Dock 5. Call 30 minutes before arrival. Loading equipment available.' as pickup_instructions,
  'Metro Retail Chain' as consignee_name,
  '5678 Commerce Drive' as consignee_address,
  'New York' as consignee_city,
  'NY' as consignee_state,
  '10001' as consignee_zip,
  'Sarah Johnson' as consignee_contact_name,
  '(555) 987-6543' as consignee_contact_phone,
  'sarah.johnson@metroretail.com' as consignee_contact_email,
  'Dock 12. Appointment required. Inside delivery to warehouse floor.' as delivery_instructions,
  450 as pieces,
  25 as pallets,
  450 as boxes,
  48.0 as length,
  96.0 as width,
  102.0 as height,
  NULL as temperature,
  false as is_hazardous,
  false as is_oversized,
  'Handle with care. Fragile electronics. No stacking over 3 pallets high.' as special_instructions,
  false as requires_liftgate,
  true as requires_inside_delivery,
  true as requires_appointment,
  NULL as appointment_time
FROM public.companies c
WHERE c.company_type IN ('broker', 'both')
LIMIT 1
ON CONFLICT DO NOTHING;

-- Demo Load 2: Reefer Load (Frozen Food)
INSERT INTO public.load_marketplace (
  broker_id,
  origin,
  destination,
  weight,
  weight_kg,
  contents,
  value,
  rate,
  rate_type,
  pickup_date,
  pickup_time_window_start,
  pickup_time_window_end,
  delivery_date,
  delivery_time_window_start,
  delivery_time_window_end,
  equipment_type,
  status,
  auto_create_enabled,
  notes,
  shipper_name,
  shipper_address,
  shipper_city,
  shipper_state,
  shipper_zip,
  shipper_contact_name,
  shipper_contact_phone,
  shipper_contact_email,
  pickup_instructions,
  consignee_name,
  consignee_address,
  consignee_city,
  consignee_state,
  consignee_zip,
  consignee_contact_name,
  consignee_contact_phone,
  consignee_contact_email,
  delivery_instructions,
  pieces,
  pallets,
  boxes,
  length,
  width,
  height,
  temperature,
  is_hazardous,
  is_oversized,
  special_instructions,
  requires_liftgate,
  requires_inside_delivery,
  requires_appointment,
  appointment_time
)
SELECT 
  c.id as broker_id,
  'Dallas, TX' as origin,
  'Chicago, IL' as destination,
  '18 tons' as weight,
  16329 as weight_kg,
  'Frozen food products' as contents,
  75000.00 as value,
  3200.00 as rate,
  'flat' as rate_type,
  CURRENT_DATE + INTERVAL '2 days' as pickup_date,
  '06:00:00'::TIME as pickup_time_window_start,
  '14:00:00'::TIME as pickup_time_window_end,
  CURRENT_DATE + INTERVAL '5 days' as delivery_date,
  '08:00:00'::TIME as delivery_time_window_start,
  '15:00:00'::TIME as delivery_time_window_end,
  'reefer' as equipment_type,
  'available' as status,
  true as auto_create_enabled,
  'Temperature controlled: -10°F. Requires liftgate at both ends.' as notes,
  'Cold Storage Solutions' as shipper_name,
  '8900 Freezer Lane' as shipper_address,
  'Dallas' as shipper_city,
  'TX' as shipper_state,
  '75201' as shipper_zip,
  'Mike Thompson' as shipper_contact_name,
  '(555) 234-5678' as shipper_contact_phone,
  'mike.thompson@coldstorage.com' as shipper_contact_email,
  'Cold dock 3. Pre-cool trailer to -10°F before arrival. Seal inspection required.' as pickup_instructions,
  'Midwest Grocers' as consignee_name,
  '2345 Distribution Way' as consignee_address,
  'Chicago' as consignee_city,
  'IL' as consignee_state,
  '60601' as consignee_zip,
  'Lisa Chen' as consignee_contact_name,
  '(555) 876-5432' as consignee_contact_phone,
  'lisa.chen@midwestgrocers.com' as consignee_contact_email,
  'Refrigerated dock 7. Maintain temperature. Liftgate delivery to cold storage.' as delivery_instructions,
  320 as pieces,
  20 as pallets,
  320 as boxes,
  53.0 as length,
  102.0 as width,
  110.0 as height,
  -10 as temperature,
  false as is_hazardous,
  false as is_oversized,
  'Maintain -10°F throughout transit. Temperature logs required. No delays.' as special_instructions,
  true as requires_liftgate,
  true as requires_inside_delivery,
  false as requires_appointment,
  NULL as appointment_time
FROM public.companies c
WHERE c.company_type IN ('broker', 'both')
LIMIT 1
ON CONFLICT DO NOTHING;

-- Demo Load 3: Flatbed Load (Construction Equipment)
INSERT INTO public.load_marketplace (
  broker_id,
  origin,
  destination,
  weight,
  weight_kg,
  contents,
  value,
  rate,
  rate_type,
  pickup_date,
  pickup_time_window_start,
  pickup_time_window_end,
  delivery_date,
  delivery_time_window_start,
  delivery_time_window_end,
  equipment_type,
  status,
  auto_create_enabled,
  notes,
  shipper_name,
  shipper_address,
  shipper_city,
  shipper_state,
  shipper_zip,
  shipper_contact_name,
  shipper_contact_phone,
  shipper_contact_email,
  pickup_instructions,
  consignee_name,
  consignee_address,
  consignee_city,
  consignee_state,
  consignee_zip,
  consignee_contact_name,
  consignee_contact_phone,
  consignee_contact_email,
  delivery_instructions,
  pieces,
  pallets,
  boxes,
  length,
  width,
  height,
  temperature,
  is_hazardous,
  is_oversized,
  special_instructions,
  requires_liftgate,
  requires_inside_delivery,
  requires_appointment,
  appointment_time
)
SELECT 
  c.id as broker_id,
  'Phoenix, AZ' as origin,
  'Atlanta, GA' as destination,
  '45 tons' as weight,
  40823 as weight_kg,
  'Construction equipment and materials' as contents,
  250000.00 as value,
  5200.00 as rate,
  'flat' as rate_type,
  CURRENT_DATE + INTERVAL '4 days' as pickup_date,
  '07:00:00'::TIME as pickup_time_window_start,
  '16:00:00'::TIME as pickup_time_window_end,
  CURRENT_DATE + INTERVAL '7 days' as delivery_date,
  '08:00:00'::TIME as delivery_time_window_start,
  '17:00:00'::TIME as delivery_time_window_end,
  'flatbed' as equipment_type,
  'available' as status,
  true as auto_create_enabled,
  'Oversized load. Requires permits. Weekend delivery preferred.' as notes,
  'Southwest Construction Supply' as shipper_name,
  '3456 Builder Avenue' as shipper_address,
  'Phoenix' as shipper_city,
  'AZ' as shipper_state,
  '85001' as shipper_zip,
  'Robert Williams' as shipper_contact_name,
  '(555) 345-6789' as shipper_contact_phone,
  'robert.williams@swconstruction.com' as shipper_contact_email,
  'Yard 2. Crane available for loading. Driver must assist with securing load.' as pickup_instructions,
  'Southeast Builders Inc' as consignee_name,
  '7890 Construction Road' as consignee_address,
  'Atlanta' as consignee_city,
  'GA' as consignee_state,
  '30301' as consignee_zip,
  'David Brown' as consignee_contact_name,
  '(555) 765-4321' as consignee_contact_phone,
  'david.brown@sebuilders.com' as consignee_contact_email,
  'Job site delivery. Call 2 hours before arrival. Weekend delivery OK.' as delivery_instructions,
  12 as pieces,
  NULL as pallets,
  NULL as boxes,
  48.0 as length,
  102.0 as width,
  13.5 as height,
  NULL as temperature,
  false as is_hazardous,
  true as is_oversized,
  'Oversized load - 13.5ft height. Permits required for all states. Escort may be needed.' as special_instructions,
  false as requires_liftgate,
  false as requires_inside_delivery,
  false as requires_appointment,
  NULL as appointment_time
FROM public.companies c
WHERE c.company_type IN ('broker', 'both')
LIMIT 1
ON CONFLICT DO NOTHING;

-- Demo Load 4: Short Haul Dry Van
INSERT INTO public.load_marketplace (
  broker_id,
  origin,
  destination,
  weight,
  weight_kg,
  contents,
  value,
  rate,
  rate_type,
  pickup_date,
  pickup_time_window_start,
  pickup_time_window_end,
  delivery_date,
  delivery_time_window_start,
  delivery_time_window_end,
  equipment_type,
  status,
  auto_create_enabled,
  notes,
  shipper_name,
  shipper_address,
  shipper_city,
  shipper_state,
  shipper_zip,
  shipper_contact_name,
  shipper_contact_phone,
  shipper_contact_email,
  pickup_instructions,
  consignee_name,
  consignee_address,
  consignee_city,
  consignee_state,
  consignee_zip,
  consignee_contact_name,
  consignee_contact_phone,
  consignee_contact_email,
  delivery_instructions,
  pieces,
  pallets,
  boxes,
  length,
  width,
  height,
  temperature,
  is_hazardous,
  is_oversized,
  special_instructions,
  requires_liftgate,
  requires_inside_delivery,
  requires_appointment,
  appointment_time
)
SELECT 
  c.id as broker_id,
  'San Francisco, CA' as origin,
  'Sacramento, CA' as destination,
  '15 tons' as weight,
  13608 as weight_kg,
  'Office furniture and supplies' as contents,
  45000.00 as value,
  1800.00 as rate,
  'flat' as rate_type,
  CURRENT_DATE + INTERVAL '1 day' as pickup_date,
  '09:00:00'::TIME as pickup_time_window_start,
  '15:00:00'::TIME as pickup_time_window_end,
  CURRENT_DATE + INTERVAL '2 days' as delivery_date,
  '10:00:00'::TIME as delivery_time_window_start,
  '16:00:00'::TIME as delivery_time_window_end,
  'dry_van' as equipment_type,
  'available' as status,
  true as auto_create_enabled,
  'Inside delivery required. Call before arrival.' as notes,
  'Pacific Office Solutions' as shipper_name,
  '123 Business Park Drive' as shipper_address,
  'San Francisco' as shipper_city,
  'CA' as shipper_state,
  '94102' as shipper_zip,
  'Jennifer Lee' as shipper_contact_name,
  '(555) 456-7890' as shipper_contact_phone,
  'jennifer.lee@pacificoffice.com' as shipper_contact_email,
  'Warehouse dock. Standard dock height. No special requirements.' as pickup_instructions,
  'State Capital Business Center' as consignee_name,
  '456 Government Plaza' as consignee_address,
  'Sacramento' as consignee_city,
  'CA' as consignee_state,
  '95814' as consignee_zip,
  'Michael Davis' as consignee_contact_name,
  '(555) 654-3210' as consignee_contact_phone,
  'michael.davis@statecapital.com' as consignee_contact_email,
  'Inside delivery to 3rd floor. Elevator access available. Call 1 hour before arrival.' as delivery_instructions,
  280 as pieces,
  18 as pallets,
  280 as boxes,
  48.0 as length,
  96.0 as width,
  102.0 as height,
  NULL as temperature,
  false as is_hazardous,
  false as is_oversized,
  'Fragile items. Handle with care. Inside delivery required.' as special_instructions,
  false as requires_liftgate,
  true as requires_inside_delivery,
  true as requires_appointment,
  (CURRENT_DATE + INTERVAL '2 days' + INTERVAL '10 hours')::TIMESTAMP WITH TIME ZONE as appointment_time
FROM public.companies c
WHERE c.company_type IN ('broker', 'both')
LIMIT 1
ON CONFLICT DO NOTHING;

-- Demo Load 5: Per Mile Rate Load
INSERT INTO public.load_marketplace (
  broker_id,
  origin,
  destination,
  weight,
  weight_kg,
  contents,
  value,
  rate,
  rate_type,
  pickup_date,
  pickup_time_window_start,
  pickup_time_window_end,
  delivery_date,
  delivery_time_window_start,
  delivery_time_window_end,
  equipment_type,
  status,
  auto_create_enabled,
  notes,
  shipper_name,
  shipper_address,
  shipper_city,
  shipper_state,
  shipper_zip,
  shipper_contact_name,
  shipper_contact_phone,
  shipper_contact_email,
  pickup_instructions,
  consignee_name,
  consignee_address,
  consignee_city,
  consignee_state,
  consignee_zip,
  consignee_contact_name,
  consignee_contact_phone,
  consignee_contact_email,
  delivery_instructions,
  pieces,
  pallets,
  boxes,
  length,
  width,
  height,
  temperature,
  is_hazardous,
  is_oversized,
  special_instructions,
  requires_liftgate,
  requires_inside_delivery,
  requires_appointment,
  appointment_time
)
SELECT 
  c.id as broker_id,
  'Denver, CO' as origin,
  'Portland, OR' as destination,
  '16 tons' as weight,
  14515 as weight_kg,
  'Textile products' as contents,
  60000.00 as value,
  2.15 as rate,
  'per_mile' as rate_type,
  CURRENT_DATE + INTERVAL '3 days' as pickup_date,
  '08:00:00'::TIME as pickup_time_window_start,
  '16:00:00'::TIME as pickup_time_window_end,
  CURRENT_DATE + INTERVAL '6 days' as delivery_date,
  '09:00:00'::TIME as delivery_time_window_start,
  '17:00:00'::TIME as delivery_time_window_end,
  'dry_van' as equipment_type,
  'available' as status,
  true as auto_create_enabled,
  'Per mile rate. Estimated distance: 1,200 miles. Payment upon delivery.' as notes,
  'Mountain Textiles' as shipper_name,
  '5678 Fabric Street' as shipper_address,
  'Denver' as shipper_city,
  'CO' as shipper_state,
  '80201' as shipper_zip,
  'Amanda Wilson' as shipper_contact_name,
  '(555) 567-8901' as shipper_contact_phone,
  'amanda.wilson@mountaintextiles.com' as shipper_contact_email,
  'Dock 4. Standard business hours. No appointment needed.' as pickup_instructions,
  'Pacific Coast Fabrics' as consignee_name,
  '8901 Textile Way' as consignee_address,
  'Portland' as consignee_city,
  'OR' as consignee_state,
  '97201' as consignee_zip,
  'Chris Anderson' as consignee_contact_name,
  '(555) 543-2109' as consignee_contact_phone,
  'chris.anderson@pacificfabrics.com' as consignee_contact_email,
  'Warehouse dock. Standard delivery. Payment COD.' as delivery_instructions,
  240 as pieces,
  15 as pallets,
  240 as boxes,
  48.0 as length,
  96.0 as width,
  102.0 as height,
  NULL as temperature,
  false as is_hazardous,
  false as is_oversized,
  'Payment upon delivery. COD accepted.' as special_instructions,
  false as requires_liftgate,
  false as requires_inside_delivery,
  false as requires_appointment,
  NULL as appointment_time
FROM public.companies c
WHERE c.company_type IN ('broker', 'both')
LIMIT 1
ON CONFLICT DO NOTHING;

-- Verify the loads were inserted
SELECT 
  id,
  origin,
  destination,
  equipment_type,
  rate,
  rate_type,
  status,
  pickup_date,
  shipper_name,
  consignee_name
FROM public.load_marketplace
WHERE broker_id IN (SELECT id FROM public.companies WHERE company_type IN ('broker', 'both'))
ORDER BY created_at DESC
LIMIT 10;
